# Docker compose file for the application.

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 8080:8080
    links:
      - solr

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  solr:
    build: ./solr
    ports:
     - "8983:8983"
    volumes:
      - ./volumes/solr_backup:/solr_backup
    links:
      - zookeeper
    command: "bash -c './post-hooks.sh & /opt/solr/bin/solr start -f -z zookeeper:2181 -Denable.packages=true -Dbootstrap_confdir=/solr-config/index/conf'"

  solr-proxy:
    build: ./solr-proxy
    ports:
      - "8000:80"
    links:
      - solr

  init:
    build:
      context: ./ocr
      dockerfile: init/Dockerfile
    links:
      - solr
      - zookeeper

  tika:
    image: apache/tika:1.28-full
    ports:
      - "9998:9998"
